addr = "0.0.0.0:8081"
hello_wav = "hello.wav"

# [tts]
# platform = "Groq"
# api_key = "gsk_xxx"
# model = "playai-tts"
# voice = "Aaliyah-PlayAI"

# [tts]
# platform = "StreamGSV"
# url = "http://localhost:8000/v1/audio/speech"
# speaker = "speaker2"

[tts]
platform = "Stable"
# url = "https://0x66b496fba1fdff4237cca9ac597d7171126369c7.gaia.domains/v1/audio/speech"
url = "http://localhost:8000/v1/audio/speech"
speaker = "speaker2"


# [asr]
# url = "https://api.groq.com/openai/v1/audio/transcriptions"
# lang = "zh"
# api_key = "gsk_xxx"
# model = "whisper-large-v3-turbo"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

[asr]
url = "https://whisper.gaia.domains/v1/audio/transcriptions"
lang = "auto"
prompt = "Hello\n你好\n(noise)\n(bgm)\n(silence)\n"
# vad_url = "http://localhost:9093/v1/audio/vad"
vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

# [llm]
# llm_chat_url = "https://api.groq.com/openai/v1/chat/completions"
# api_key = "gsk_xxx"
# model = "gemma2-9b-it"
# history = 1

[llm]
llm_chat_url = "http://198.18.0.1:1234/v1/chat/completions"
api_key = ""
model = "qwen3-4b-thinking-2507"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
你叫胡桃，是一个优秀的翻译官。你现在的任务是，把我给你的中文翻译成英文，并且用英文回答我。

你说话时必须满足以下格式
第一行是你当前的状态或者要执行的动作，第二行开始是你的对话内容

比如：
[翻译]
这句话的翻译是 "I am a translator"。
"""

[[llm.sys_prompts]]
role = "user"
content = """
我是一个翻译官
"""

[[llm.sys_prompts]]
role = "assistant"
content = """
[翻译]
这句话的翻译是 "I am a translator"。
"""

