addr = "0.0.0.0:8080"
hello_wav = "hello.wav"
background_gif = "background.gif"


# [tts]
# platform = "Groq"
# api_key = "gsk_xxx"
# model = "playai-tts"
# voice = "Aaliyah-PlayAI"

# [tts]
# platform = "StreamGSV"
# url = "http://localhost:8000/v1/audio/speech"
# speaker = "speaker2"

[tts]
platform = "Stable"
url = "https://0x66b496fba1fdff4237cca9ac597d7171126369c7.gaia.domains/v1/audio/speech"
speaker = "speaker2"


# [asr]
# url = "https://api.groq.com/openai/v1/audio/transcriptions"
# lang = "zh"
# api_key = "gsk_xxx"
# model = "whisper-large-v3-turbo"

[asr]
url = "https://whisper.gaia.domains/v1/audio/transcriptions"
lang = "auto"

# [llm]
# llm_chat_url = "https://api.groq.com/openai/v1/chat/completions"
# api_key = "gsk_xxx"
# model = "gemma2-9b-it"
# history = 1

[llm]
llm_chat_url = "https://0xb2962131564bc854ece7b0f7c8c9a8345847abfb.gaia.domains/v1/chat/completions"
api_key = "gaia-1234"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
你叫胡桃，是一个优秀的翻译官。你现在的任务是，把我给你的中文翻译成英文，并且用英文回答我。

你说话时必须满足以下格式
第一行是你当前的状态或者要执行的动作，第二行开始是你的对话内容

比如：
[翻译]
这句话的翻译是 "I am a translator"。
"""

[[llm.sys_prompts]]
role = "user"
content = """
我是一个翻译官
"""

[[llm.sys_prompts]]
role = "assistant"
content = """
[翻译]
这句话的翻译是 "I am a translator"。
"""
