[env]
RUST_LOG = "debug"

[tasks.server]
description = "Build release binary and run server with nohup"
dependencies = ["build-release"]
script = [
    "mkdir -p logs",
    "export RUST_LOG=debug",
    "nohup target/release/echokit_server > logs/echokit.out.log 2> logs/echokit.err.log &",
    "sleep 0.5",
    "pgrep -n 'echokit_server' > echokit.pid",
    "echo 'Server started (PID: $(cat echokit.pid))'",
]

[tasks.build-release]
description = "Build the release binary"
command = "cargo"
args = ["build", "--release"]

[tasks.server-stop]
description = "Stop the running server"
script = [
    "pkill -f echokit_server",
    "echo \"Server stopped\""
]

[tasks.server-status]
description = "Check if server is running"
script = [
    "pgrep -f echokit_server > /dev/null && echo \"Server is running\" || echo \"Server is not running\""
]

[tasks.server-log]
description = "Monitor server log"
script = [
    "tail -f logs/echokit.out.log"
]
